// <auto-generated />
using GuideAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuideAPI.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303175246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuideAPI.DAL.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.FavoritePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "PlaceId")
                        .IsUnique();

                    b.ToTable("FavoritePlaces");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.UserPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NameOfPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo1")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Photo2")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Photo3")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Photo4")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Photo5")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("UserPlaces");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExcludedTypes")
                        .HasColumnType("text");

                    b.Property<string>("IncludedTypes")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxResultCount")
                        .HasColumnType("integer");

                    b.Property<bool>("OpenNow")
                        .HasColumnType("boolean");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<string>("RankPreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.FavoritePlace", b =>
                {
                    b.HasOne("GuideAPI.DAL.Entities.TelegramUser", "TelegramUser")
                        .WithMany("FavoritePlaces")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.UserSettings", b =>
                {
                    b.HasOne("GuideAPI.DAL.Entities.TelegramUser", "TelegramUser")
                        .WithOne("Settings")
                        .HasForeignKey("GuideAPI.DAL.Entities.UserSettings", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("GuideAPI.DAL.Entities.TelegramUser", b =>
                {
                    b.Navigation("FavoritePlaces");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
